# Share index versions, state names, and size limits across backend modules.
# The cross-language contract check compares these values with TypeScript.

from typing import Literal


DEVMATE_KNOWLEDGE_INDEX_API_VERSION = 1
MAX_WORKSPACE_KEY_CHARACTERS = 256
MAX_WORKSPACE_ROOT_CHARACTERS = 4_096
MAX_RELATIVE_PATH_CHARACTERS = 1_024
MAX_LANGUAGE_ID_CHARACTERS = 128
MAX_CONTENT_HASH_CHARACTERS = 256
MAX_CHUNK_STABLE_ID_CHARACTERS = 1_280
MAX_CHUNK_CHARACTERS = 20_000
MAX_CHUNKS_PER_FILE = 512
MAX_FILE_CHANGES_PER_BATCH = 500
MAX_INDEX_BATCH_CONTENT_CHARACTERS = 4_000_000
MAX_LEXICAL_QUERY_CHARACTERS = 2_000
MAX_LEXICAL_QUERY_TERMS = 32
MAX_LEXICAL_RESULTS = 100
MAX_SEMANTIC_QUERY_CHARACTERS = 2_000
MAX_SEMANTIC_RESULTS = 100
MAX_INDEX_INTEGER = 9_007_199_254_740_991
MAX_SQLITE_INTEGER = 9_223_372_036_854_775_807

IndexState = Literal["empty", "indexing", "ready", "stale", "failed"]
INDEX_STATES: tuple[IndexState, ...] = (
    "empty",
    "indexing",
    "ready",
    "stale",
    "failed",
)
